
go:
	python3 day04.py
	@echo


watch:
	../../tools/watch day04.py make --no-print-directory go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2024/day/4/input >input.txt
	chmod 444 input.txt
