
go:
	python3 day09.py
	@echo


watch:
	../../tools/watch day09.py make --no-print-directory go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2022/day/9/input >input.txt
	chmod 444 input.txt
