


go:
	python day23.py input.txt
        # bot with max radius is pos=<39388501,117625326,59107899>, r=99445291
        # 297 bots are in range

s:
	python day23.py -d sample.txt >/tmp/sample.out
	diff sample.txt /tmp/sample.out

