
p2:
	python day23.py -2 input.txt
	# python day23.py -2 input.txt | tee part2.out
	# too high: 126751959
	# too high: 126751889
	# wrong: 126624512

part1:
	python day23.py input.txt
        # bot with max radius is pos=<39388501,117625326,59107899>, r=99445291
        # 297 bots are in range

s:
	python day23.py -d sample.txt >/tmp/sample.out
	diff sample.out /tmp/sample.out
	python day23.py -d -t sample2.txt
