
go:
	python3 day17.py


watch:
	../tmpl/watch day17.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2020/day/17/input >input.txt
	chmod 444 input.txt
