
go:
	python3 day01.py


watch:
	../../tools/watch day01.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2021/day/1/input >input.txt
	chmod 444 input.txt
