
go:
	python3 day13.py


watch:
	../tmpl/watch make go


get:
	mv $$HOME/Downloads/input.txt .
	#curl -H "Cookie: $$(cat $HOME/.cookie_aoc)" https://adventofcode.com/2020/day/13/input >input.txt
	chmod 444 input.txt
