
go:
	python3 day20.py


watch:
	../tmpl/watch day20.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2020/day/20/input >input.txt
	chmod 444 input.txt
