
go:
	python3 day02.py


watch:
	../../tools/watch day02.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	sleep 2
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2021/day/2/input >input.txt
	chmod 444 input.txt
