
go:
	python3 day10.py
	@echo


watch:
	../../tools/watch day10.py make --no-print-directory go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2021/day/10/input >input.txt
	chmod 444 input.txt
