
go:
	python3 day11.py


watch:
	../tmpl/watch make go


get:
	# mv $HOME/Downloads/input.txt .
	curl -H "Cookie: $(cat $HOME/.cookie_aoc)" https://adventofcode.com/2020/day/11/input >input.txt
	chmod 444 input.txt
