
go:
	python3 day05.py


watch:
	../../tools/watch day05.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2021/day/5/input >input.txt
	chmod 444 input.txt
