
go:
	python3 day17.py
	@echo


watch:
	../../tools/watch day17.py make --no-print-directory go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2021/day/17/input >input.txt
	chmod 444 input.txt
