
go:
	python3 day13.py
	@echo


watch:
	../../tools/watch day13.py make --no-print-directory go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2023/day/13/input >input.txt
	chmod 444 input.txt
