
go:
	python3 day@N@.py


watch:
	../tmpl/watch day@N@.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2020/day/@N@/input >input.txt
	chmod 444 input.txt
