
all_tests:	aoc_test elf_image_test grid_test memoized_test qparser_test reader_test

aoc_test:
	PYTHONPATH=.. python3 aoc.py

elf_image_test:
	python3 elf_image.py

grid_test:
	python3 grid.py

memoized_test:
	python3 memoized.py

qparser_test:
	python3 qparser.py

reader_test:
	python3 reader.py
