#!/bin/bash

file=$1
shift
cmd="$*"
MOD=/tmp/.last_aoc


while : ; do
  sleep 1
  if [[ $file -nt "$MOD" ]] ; then
    touch "$MOD"
    echo ============================== $(date)
    timeout 120 $cmd
  fi
done
