#!/bin/bash

file=$1
shift
cmd="$*"
MOD=/tmp/.last_aoc

TIMEOUT="timeout 120"
if [[ $(uname) == 'Darwin' ]] ; then
  TIMEOUT=""
fi


while : ; do
  sleep 1
  if [[ $file -nt "$MOD" ]] ; then
    touch "$MOD"
    echo ============================== $(date)
    $TIMEOUT $cmd
  fi
done
