
go:
	python3 day03.py


watch:
	../../tools/watch day03.py make go


get:
	# mv $$HOME/Downloads/input.txt .
	curl -H "Cookie: $$(cat $$HOME/.cookie_aoc)" https://adventofcode.com/2021/day/3/input >input.txt
	chmod 444 input.txt
